#!/bin/bash -x

publishNightly () {
  [[ $# -eq 4 ]] || {
    cat <<EOM
publishNightly <publish> <jobName> <buildNr> <scaladocDir>
 - <publish> if not "true" then this function does nothing
 - <jobName> name of jenkins job that built the distribution
 - <buildNr> build number
 - <scaladocDir> the directory name to which scaladoc is published
EOM
    exit 1
  }

  publish=$1
  jobName=$2
  buildNr=$3
  scaladocDir=$4

  if [[ $publish == "true" ]]; then
    rm -rf jenkins-artifacts jenkins-artifacts.tgz
    wgetFile job/$jobName/$buildNr/artifact/jenkins-artifacts.tgz
    tar xzf jenkins-artifacts.tgz

    cd jenkins-artifacts

    # Archive Scala nightly distribution (no-op by now, we no longer publish nightly tgz/zip/...)
    if [[ -d dists/archives ]]; then
      rsync -az dists/archives/ "$nightly_rsync_dest/distributions"
    fi

    # publish scaladoc nightlies
    if [[ -d build/scaladoc ]]; then
      rsync -az build/scaladoc/ "$nightly_rsync_dest/$scaladocDir"
    fi

    # push to the maven repository. in 2.11.x and above, we've already published during the main job
    if [[ -e dists/maven/latest/build.xml ]]; then
      cd dists/maven/latest
      ant deploy -Dsettings.file=$maven_settings_file
    fi
  fi
}
